README.rst, linux/storage/swap.sls
The idea here is to be able to add swap partitions rather than files. In our use case we don't want to snapshot a lv with a swap file present.
=> add swap partition support

linux/meta/heka.yml
This commit removes the alarm-related filter configuration from `meta/heka.yml`. Alarms will be defined in a different way (still under discussion).
=> Remove the alarm-related filters

linux/meta/heka.yml
This fixes the decoder name in `meta/heka.yml`.
=> Fix decoder name

linux/meta/heka.yml
This is required to make the `log_collector` start.
=> Set "hostname" in the linux_hdd_errors|counters filters

linux/meta/heka.yml
If `system.timezone` is defined this sets `tz` in the syslog/system decoder configuration. This is required to get correct dates in log messages sent to Elasticsearch.
=> Add timezone to syslog decoder config

linux/map.jinja
There is an error in salt doc. Hashing-alghoritm is correct, https://github.com/saltstack/salt/blob/90bbf8dc4f3c9eba09107821309ff7b07df93c3b/salt/modules/debian_ip.py#L1045
=> xmit_hash_policy to hashing-alghoritm

_modules/netlink.py, linux/files/collectd_netlink.conf, linux/map.jinja, linux/meta/collectd.yml
This patch replaces the "interface" collectd plugin by the "netlink" one. The "netlink" plugin provides the same metrics as "interface" but plus other metrics such as the number of dropped packets.
=> Use netlink collectd plugin instead of interface

linux/meta/heka.yml
This is now handled by the Heka formula the same way for all the Heka sandbox decoders. Depends on https://github.com/tcpcloud/salt-formula-heka/pull/20.
=> Remove Heka decoder tz handling

linux/meta/heka.yml
The support for collecting syslog is going to be moved to the rsyslog formula.
See https://github.com/tcpcloud/salt-formula-rsyslog/pull/1 for the corresponding PR to the rsyslog formula.
=> Remove support for log_collector

README.rst, linux/files/setup-loopback-device.systemd, linux/files/setup-loopback-device.upstart, linux/map.jinja, linux/storage/init.sls, linux/storage/loopback.sls
This state allows to configure loopback device(s). This isn't meant to
be used in production but offers a cheap way to test Cinder with LVM
volumes.
=> Add linux.storage.loopback state

linux/network/interface.sls
If you have a second interface, that is also connecting to a (different) ovs_bridge, then it fails compilation:
Data failed to compile:                                                                                       │
----------                                                                                                        │
Rendering SLS 'base:linux.network.interface' failed: Conflicting ID 'add_int_to_ovs_bridge_br-prv'            │
Proposed pull request should fix this.
=> In setups with more than 1 interface / bond, it does not work

linux/network/hostname.sls
safe way to avoid non necessary hostname change.. 
For reviewer: bit hesitate between  ```$(hostname -s)``` vs used $(hostname)
=> dont touch hostname if not needed

linux/system/repo.sls
When someone add https repository, the state will fail, becase it is not able to work without apt-transport-https which is installed in package state.
=> require linux_packages install in repo state

linux/network/interface.sls
We need to save our manualy managed interfaces to different directory to
workaround salt bug that causes interface deconfiguration in
/etc/network/interfaces for interfaces manualy configured in
/etc/network/interfaces.d
=> Workaround for salt network interfaces bug

README.rst, linux/files/60-net-txqueue.rules, linux/network/interface.sls
Config:
linux:
network:
tap_custom_txqueuelen: 10000
in case of configuration parameter defined will create file:
/etc/udev/rules.d/60-net-txqueue.rules
with content:
KERNEL==”tap[0-9a-z\-]*", RUN+="/sbin/ip link set %k txqueuelen 10000"
=> Feature: automatically set txqueuelen for all tap* network interfaces

linux/meta/sensu.yml
will always be defined since the default is an empty dict)
=> [MMO-132] Check the length of the dict, instead of if it's defined (it

README.rst, linux/files/governor.conf.jinja, linux/files/modprobe.conf.jinja, linux/system/cpu.sls, linux/system/kernel.sls
This commit adds 2 features:
1. Add persistent cpu governor for every cpu core on;
2. Control /etc/modprobe.d/ directory to set any options that maybe required.
=> RIL-267 Adding cpu governor and kernel module opts

linux/network/interface.sls
Change of mtu is not handled by reclass. Example interface:
```
br_ctl:
enabled: true
type: bridge
proto: static
mtu: 1450
address: ${_param:single_address}
gateway: ${_param:ctl_gateway}
netmask: ${_param:control_network_netmask}
use_interfaces:
- ${_param:primary_first_nic}
```
=> Adds ability to set mtu in reclass

linux/storage/mount.sls
Usually you need define order for mounting volumes in one path like mount first /opt and then /opt/cms etc.
=> sort mount points

README.rst, linux/storage/disk.sls
Hi guys :)
I extend storage.disk pillar with another option, because I would like to start creating partiions on disk from some point, for example from 2048. 
Example:
storage:
enabled: true
disk:
/dev/sdb:
startsector: 1      #Value in MB to start from sector 2048
type: gpt
partitions:
- size: 256000    #Value in MB
mkfs: True
type: xfs
In environment where I use a lot of virtual machines, setting startsector give me small boost with using partition alligment.
http://www.blueshiftblog.com/?p=300
I add this change to salt-formula, and I think that will be good to share this with you :)
Would you like to add this option in seperate example in readme?
That's my first pull request in salt community, and I will be happy for your opinions and comments.
=> add startsector for partitions

linux/system/kernel.sls, tests/pillar/system.sls
Adds elevator parameter to Linux Kernel command line to configure default queue scheduler at boot time.
One can already configure queue scheduler using linux.system.sysfs.scheduler, but has to define every block device separatly.
=> Add elevator parameter to GRUB_CMDLINE_LINUX_DEFAULT

linux/system/kernel.sls
linux.system.kernel state results in conflicting ids when both isolcpu and elevator pillar are set.
=> fix Conflicting ID for duplicated include of linux.system.grub

README.rst, linux/system/init.sls, linux/system/ld.sls
Hello,
this merge request gives the ability to add shared libraries without set LD_LIBRARY_PATH variable. In general there a multiple ways to add additional non standard library locations. But this seems to me the most common way to persist this change:
1. Generate file in /etc/ld.so.conf.d/
2. Update /etc/ld.so.cache with ldconfig command
**example pillars:** 
```
linux:
system:
enabled: True
ld:
libraries:
java:
- /usr/lib/jvm/jre-openjdk/lib/amd64/server
- /opt/java/jre/lib/amd64/server
```
=> add additional shared libraries

linux/network/dpdk.sls, linux/system/hugepages.sls
To get a working ovs-dpdk without forcing a system reboot, we need to:
- set hugepages number via sysctl, so we can use them right away;
- handle ovs-vswitchd alternative;
=> ovs-dpdk should work without system reboot

linux/network/interface.sls
Previously, setting up routes did not allow passing 'require_reboot',
so each route change would lead to a networking service restart,
rendering interface configuration options like 'noifupdown' useless.
Allow disabling network restart per-interface using the existing
'noifupdown' option.
This caused me some issues with the following use-case:
1. node provisioned by MaaS, dhcp on eth0
2. trying to configure a bridge on top of eth0 (hence moving DHCP from eth0 to that bridge)
3. set all interfaces to 'noifupdown', planning to let the config kick in after a reboot
4. trying to configure a route on another interface at the same will restart the networking service, which obviously breaks;
Using 'noifupdown' seems like a good idea to me, but we can decouple them if needed ...
=> routes: Skip network restart on 'noifupdown'

linux/system/repo.sls
Salt has problem to fetch repo key from behind proxy with this simple state:
```
pkgrepo.managed:
- key_url: some_url
```
This workaround enables adding repo and fetch it's gpg key from behind proxy, if proxy environment is properly configured (`curl -s some_url` works).
=> Workaround for fetching repo keys via proxy.

linux/system/repo.sls
Change-Id: Id5b5a44f3dfbbdd60442fd2f273b72557fa9e191
(change will come from Mirantis gerrit once it pass tests)
=> Fix, system.repo don't use curl on fixed pkgrepo.manage

linux/system/user.sls
When I define user.gid I don't expecting that "default" group will have same name as name of user, so the option "gid_from_name: true" is unnecessary.
=> change logic when I define user.gid

linux/files/openvswitch-switch.systemd, linux/network/openvswitch.sls
This workaround is necessary in case of OVN networking in Openstack. Usually hostname of a server is in short form, but in Ovs table Open_vSwitch is always presented fqdn name. This mismatch prevent neutron to set "requested-chassis" in OVN. The mismatch in hypervisor's external-ids:hostname setting
causes OVN port binding failure.
This extension of state allow set same hostname in ovs at time of starting according to server hostname.
More info bellow. This ovs patch solve the problem, but in new releases of Openvswitch:
https://patchwork.ozlabs.org/patch/979143/
=> Match server hostname in Open_vSwitch table

README.rst, tests/pillar/system.sls
Hi,
right now selinux in system is not in README and not in test pillars defined. This commit will add it to Readme and add it to test pillars.
=> Add SELinux to README and test pillars (/linux/system/selinux.sls).

linux/system/file.sls
Yaml serializer splits long lines into multiple lines, which causes salt
parsing of generated yaml to fail.
=> Use json serializer instead of yaml to fix serialization of long lines

linux/system/user.sls
So that the state won't fail if the parent directory of the home directory does not exist.
=> Create user home parent dir if makedirs is True

linux/map.jinja
LVM is failed on Debian Buster:
```
ID: lvm_services
Function: service.running
Name: lvm2-lvmetad
Result: False
Comment: Failed to start lvm2-lvmetad.service: Unit lvm2-lvmetad.service not found.
Started: 15:43:04.025625
Duration: 39.358 ms
Changes:   
```
I defined a new service list for Debian Buster
=> fix(storage): Define LVM serive list for Debian 10

linux/system/directory.sls
Update will prevent errors if state is defined but not defined directory pillar.
If directory pillar is not defined customers will receive such errors:
`Rendering SLS 'base:linux.system.directory' failed: Jinja variable 'dict object' has no attribute 'directory'`
=> Add verification that directory pillar is not empty

.travis.yml, README.rst, linux/files/journal.conf, linux/system/auth/duo.sls, linux/system/journal.sls, linux/system/systemd.sls, tests/pillar/system.sls
This settings theoretically maybe could be added to systemd main settings, but documentation (https://www.freedesktop.org/software/systemd/man/journald.conf.html) says it should be in one of:
/etc/systemd/journald.conf
/etc/systemd/journald.conf.d/*.conf
/run/systemd/journald.conf.d/*.conf
/usr/lib/systemd/journald.conf.d/*.conf
no tests were added as dockers doesn't have systemd :(
=> Add journal settings

README.rst, linux/system/file.sls, linux/system/job.sls
Added the opportunity to set a job with a special keyword like '@reboot' or '@hourly'. Quotes must be used, otherwise PyYAML will strip the '@' sign.
/path/to/cron/script:
cron.present:
- user: root
- special: '@hourly'
https://docs.saltstack.com/en/master/ref/states/all/salt.states.cron.html
=> Create @reboot .... Cron jobs

_modules/ovs_config.py
Should solve this warning:
```
[WARNING ] /var/cache/salt/minion/extmods/modules/ovs_config.py:18: DeprecationWarning: Use of 'salt.utils.which' detected. This function has been moved to 'salt.utils.path.which' as of Salt 2018.3.0. This warning will be removed in Salt Neon.
```
=> fix(deprecation): update to new method

linux/storage/swap.sls
Maintains default behavior while also allowing swap to be disabled entirely by setting `linux.storage.swap.enabled: false`. Setting back to true uses the original code path to parse the devices in `swap.items()`.
=> Allow swap to be completely disabled via `swapoff -a`

linux/network/host.sls, linux/network/openvswitch.sls, linux/storage/disk.sls, linux/storage/swap.sls, linux/system/cpu.sls, linux/system/repo.sls, linux/system/sysfs.sls
The new syntax has been supported since ~2017.
From the docs, in case they change:
! New Style
test.random_hash:
module.run:
- test.random_hash:
- size: 42
- hash_type: sha256
! Legacy Style
test.random_hash:
module.run:
- size: 42
- hash_type: sha256
=> allow use of new state syntax for module.run

linux/system/motd.sls
For linux/system/motd.sls had a issue which, for multiple files, at every run both the cleaning (under "/etc/update-motd.d:") as well as every single file setup was triggered.
This commit solved the issue putting each managed file into the requirements of "/etc/update-motd.d:", this way it will not be deleted.
Hence again the /etc/update-motd.d has to be duplicated without "clean" parameter in order to have the dependency from the parent folder to its children files.
=> Idempotent clean dependency

linux/map.jinja
python3-apt will not be installed on debian-12/bookworm (currently testing).
This PR adds python3-apt to list of system packages - #225 is a fix for bullseye and sid only
=> fix system-pkgs for debian-12

linux/map.jinja
LVM services fail in debian-11. 
This PR adds lvm-services for bullseye, bookworm, and sid (similar to #207)
=> fix lvm_service package names for debian 11,12 and unstable

linux/map.jinja
lvm_services fail in centos-8-stream.
This PR fixes lvm-services-packages similar to #226
=> fix lvm_service package names for centos 8 stream

_modules/linux_hosts.py, linux/system/user.sls
- 'cmp' as a parameter to the sorted() function doesn't exist anymore.
- Instead, we should use 'key', which tells the sorted() function what to sort by.
- Per https://docs.python.org/3/howto/sorting.html#key-functions, we can define a function
to be run against each item in the iterable that will return a value that sorted() will
sort by.
- Since the original function seems to compare lengths in the hostname entries, we can actually
make fqdn_sort_fn() a great deal simpler than it was and get largely the same results.
=> Update Sorting Function for Python3 sorted()
