linux/meta/heka.yml
The stacklight module dir is `/usr/share/lma_collector/common`, not `/usr/share/lma_collector_modules`. This fixes it.
=> Use the proper module directory

linux/map.jinja
additional bond interface params: xmit-hash, ad_select, down/updelay, ...
=> add additional bond interface params

linux/meta/heka.yml
This filter should be configured by the heka formula itself.
=> Remove the log counter filter from meta/heka

linux/meta/heka.yml
The alerting property can be one of 'disabled', 'enabled' or
'enabled_with_notification'
=> Redefine alerting property

linux/meta/heka.yml
This commit adds more built-in alarms to the Linux formula.
=> Add more alarms

linux/storage/init.sls, linux/storage/lvm.sls
These changes are required to deploy the Cinder volume service with the LVM backend.
=> Misc fixes for LVM storage

README.rst, linux/files/90autoupdates, linux/map.jinja, linux/system/autoupdates.sls, linux/system/init.sls
only Debian-based systems are supported for now
(through unattended-upgrades package)
Closes #60.
=> Add system.autoupdates state

linux/system/package.sls
And allow to install package without specifying any version
=>  Group packages to install/remove when possible for better performance

.kitchen.yml, .travis.yml, tests/integration/system/sudoer_spec.rb, tests/pillar/network.sls, tests/pillar/storage.sls, tests/pillar/system.sls, tests/pillar/system_extra.sls
network/system covered, storage is tough to be properly tested within docker container
=> Add kitchen tests + travis ci

linux/system/repo.sls
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkgrepo.html
=> Add consolidate/clean_file/refresh_db pkgrepo options

linux/map.jinja, linux/system/package.sls, linux/system/repo.sls
=> avoid install system pkgs before repo configured

linux/system/repo.sls, tests/pillar/system.sls
=> Allow direct use of gpg key in linux.system.repo

tests/pillar/system.sls
Change-Id: I193af8b11146dd06413f199e456c47da554aaae5
=> Fix kitchen test

linux/system/user.sls
Remove sudo files for users, which still exists, but don't have enabled sudo.
=> remove sudo files for user

linux/system/repo.sls
- allow multiple repos configured on one system (nightly/testing/stable)
=> Allow override repo name

linux/system/group.sls, linux/system/job.sls, linux/system/user.sls, tests/pillar/system.sls
Change-Id: Ia086cf01fe9d03e953f7a2fe013ef170363a105a
=> Fix requirements on groups and users

linux/meta/meta.yml
Change-Id: If0ee6f1ac5ab697559fcd853225e1520de2e8c1c
=> Graph metadata

linux/network/interface.sls
Reverts salt-formulas/salt-formula-linux#111
=> Revert "Adds ability to set mtu in reclass"

linux/system/group.sls, tests/pillar/system.sls
not tested, but tests included
=> manage group user membership

linux/system/selinux.sls
I prefer that all selinux mod changes be persistent so they survive the reboot of the server.
Please check if you are ok with that.
=> make all change in selinux mode persistent

linux/system/selinux.sls
this is the pull request for #125 and will fix:
1. problems with disable selinux in pillars
2. conflicts between selinux.mode and selinux_config to write /etc/selinux/config
=> Pull Request for selinux.sls issue #125

linux/network/interface.sls
=> network.interface: strict eol pattern matching

linux/system/hugepages.sls
Needed for https://jira.opnfv.org/browse/ARMBAND-341
=> Apply the hugepages configuration for aarch64

linux/files/modprobe.conf.jinja
Old template did not render correctly
=> Fixing layout of modprobe.conf file with more than one option

README.rst, linux/system/file.sls
Ensure presence of file to be serialized through one of the serializer modules
(see: https://docs.saltstack.com/en/latest/ref/serializers/all/index.html):
=> Add support file.serialize in linux:system:file

README.rst, linux/files/openvswitch-switch.systemd, linux/network/interface.sls, linux/network/openvswitch.sls, tests/pillar/network_openvswitch.sls
Added options to create native ovs bonding inside specified ovs bridge
=> Ovs native bonding

linux/storage/lvm.sls, linux/storage/mount.sls
first create LV´s, and then mount it and then install software
=> LVM create LV´s first

linux/system/repo.sls
This will fix compile issue in #183
=> Fix for issue #183 Compile issue in linux.system.repo

linux/network/dpdk.sls, linux/network/interface.sls, linux/network/openvswitch.sls, linux/storage/lvm.sls, linux/storage/mount.sls, linux/storage/multipath.sls, linux/system/auth.sls, linux/system/autoupdates.sls, linux/system/package.sls, linux/system/repo.sls
=> Fix missing json filter to support salt v2019.2

linux/system/selinux.sls
Added posibility to disable SELinux:
- update configuration file /etc/selinux/config
- execute "setenforce 0"
=> Add posibility to disable SELinux

linux/system/file.sls
Useful if you just want to touch a file
`   file:     
touch_file:
name: /tmp/filename
contents: " "
user: root
group: root
mode: 644
replace: False
`
=> Add file.managed replace Funktion.

linux/storage/mount.sls
Thanks @thr27 for Issue and code to fix it. 
I cannot design test for that as there is no real way to mount easily NFS, but tested it on my EC2 instance and works.
=> Issue 198 multiple nfs

linux/map.jinja
Signed-off-by: Matthew Thode <mthode@mthode.org>
=> update debian 11 package names (python3-apt)

README.rst
=> Fix gpgcheck typo

linux/map.jinja
=> Ubuntu 22.04 support

linux/system/repo.sls
Disable apt-key usage when salt version is at least 3005, and the user provides 'signed-by=' in their source, and we're on a newer version of Debian or Ubuntu.
apt-key is deprecated, see the following for more context:
https://docs.saltproject.io/en/latest/ref/states/all/salt.states.pkgrepo.html#apt-key-deprecated
=> Conditionally disable apt-key usage
